spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-realm
server:
  port: 9000
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls[0]:
      name: Product Service
      url: /aggregate/product-service/v3/api-docs
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v3/api-docs
# Actuator Endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# Resilience4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 2